language:
  node_js
  - 9
# @TODO: fix sudo workaround
# https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required
cache:
  directories:
    - node_modules
install:
  - npm install -g grunt-cli
  - npm install
before_script:
  - npm run eslint:error-only
script:
  - npm run build
  - npm run functional:ci
deploy:
    # DEPLOY BUILD TO DEMO SERVER
    # this runs conditionally `on`
    # "push" events to "master" branch
  - provider: script
    script: ./scripts/jenkins-deploy.sh -b master -w
    skip_cleanup: true
    on:
      condition: $TRAVIS_EVENT_TYPE = push
      branch: master
    # NPM PUBLISH NIGHTLY DEV BUILD
    # this runs conditionally on "cron" events
    # and uses default branch "master"
  - provider: script
    script: ./scripts/publish-nightly.sh
    skip_cleanup: true
    on:
      condition: $TRAVIS_EVENT_TYPE = cron
